name: food_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  # Base
  cupertino_icons: ^1.0.8
  nb_utils: ^7.1.7+2
  intl: ^0.20.2
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.2.1
  http: ^1.4.0
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  path_drawing: ^1.0.1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0
  clippy_flutter: ^2.0.0-nullsafety.1
  # mobx_codegen: ^2.7.1
  # nb_utils: ^7.0.4
  # intl: ^0.19.0
  # flutter_vector_icons: ^2.0.0
  # google_fonts: ^6.2.1
  # http: ^1.2.2

  #State Management Technique
  # mobx: ^2.3.3+2
  # flutter_mobx: ^2.2.1+1


  # MAP
  # google_maps_flutter: ^2.9.0
  # geolocator: ^13.0.1
  # geocoding: ^3.0.0

  # FoodApp
  # path_drawing: ^1.0.1
  # cached_network_image: ^3.4.1
  # flutter_svg: ^2.0.10+1

  # clippy_flutter: ^1.1.1

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  http: ^0.13.0
  clippy_flutter : 2.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  mobx_codegen: ^2.7.1

  # mobx_codegen: ^2.6.1
  # build_runner: ^2.4.12

flutter:

  uses-material-design: true

  assets:
   - images/food/
   - images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
