name: food_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # Firebase core
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_messaging: ^15.0.0

  # ✅ Riverpod state management
  flutter_riverpod: ^2.5.1         # Latest stable as of mid-2025
  hooks_riverpod: ^2.5.1           # Same version to match
  flutter_hooks: ^0.20.5           # Compatible hooks version
  
  # Image handling
  image_picker: ^1.1.0
  cached_network_image: ^3.3.1

  # Routing
  go_router: ^13.0.0

  # UI enhancements
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.2.0
  intl: ^0.19.0
  animations: ^2.0.11

  # Charts for admin dashboard
  fl_chart: ^0.64.0

  # Form validation (optional)
  formz: ^0.6.0

  # Local storage (if needed)
  shared_preferences: ^2.2.2
  # Toast messages
  fluttertoast: ^8.2.12
  google_mobile_ads: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true




