// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKHeaFCqZYm6itbHSRe65bT_RSj6lu6g8',
    appId: '1:804369840655:web:f16b45619e95e08039c17a',
    messagingSenderId: '804369840655',
    projectId: 'inmakes-87ea0',
    authDomain: 'inmakes-87ea0.firebaseapp.com',
    storageBucket: 'inmakes-87ea0.firebasestorage.app',
    measurementId: 'G-MXLKPBGK8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvVIQJi-JZYV1b-J6epUDJtoVP040_7Oo',
    appId: '1:804369840655:android:33961f0a4351a9a939c17a',
    messagingSenderId: '804369840655',
    projectId: 'inmakes-87ea0',
    storageBucket: 'inmakes-87ea0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJZQlGHxqG645JJ6fqXVk_ifW1PVkYpsc',
    appId: '1:804369840655:ios:425c57422d07d5eb39c17a',
    messagingSenderId: '804369840655',
    projectId: 'inmakes-87ea0',
    storageBucket: 'inmakes-87ea0.firebasestorage.app',
    iosBundleId: 'com.example.task2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJZQlGHxqG645JJ6fqXVk_ifW1PVkYpsc',
    appId: '1:804369840655:ios:425c57422d07d5eb39c17a',
    messagingSenderId: '804369840655',
    projectId: 'inmakes-87ea0',
    storageBucket: 'inmakes-87ea0.firebasestorage.app',
    iosBundleId: 'com.example.task2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKHeaFCqZYm6itbHSRe65bT_RSj6lu6g8',
    appId: '1:804369840655:web:5dbc87078614e00339c17a',
    messagingSenderId: '804369840655',
    projectId: 'inmakes-87ea0',
    authDomain: 'inmakes-87ea0.firebaseapp.com',
    storageBucket: 'inmakes-87ea0.firebasestorage.app',
    measurementId: 'G-F36GV5RB9Z',
  );
}
